# This is a workflow to perform basic verification for KoLmafia ASH scripts

name: CI
env:
  MAFIA_BUILD: "1938"
  MAFIA_VERSION: "20430"
  SCRIPT_NAME: "autoscend.ash"

on: [push, pull_request]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8

    - name: Prepare KoLmafia
      run: |
        if [[ ! -f ".github/kolmafia.jar" ]]; then
          curl "https://ci.kolmafia.us/job/Kolmafia/${MAFIA_BUILD}/artifact/dist/KoLmafia-${MAFIA_VERSION}.jar" --output .github/kolmafia.jar
        fi
    
    - name: Install and verify
      run: |
        cd RELEASE

        if [[ -f "dependencies.txt" ]]; then
          # Install dependencies
          echo "Installing dependencies..."

          output_file="scripts/_ci_dependencies.ash"
          while read -r line || [ -n "$line" ]; do
            echo "cli_execute('svn checkout ${line}');" >> "$output_file"
          done < "dependencies.txt"
          echo "cli_execute('exit');" >> "$output_file"
          java -DuseCWDasROOT=true -jar ../.github/kolmafia.jar --CLI _ci_dependencies
        fi

        # Verify autoscend.ash
        echo "Verifying autoscend.ash..."
        echo "try { cli_execute('verify ${SCRIPT_NAME}'); } finally { cli_execute('exit'); }" > scripts/_ci_verify.ash
        output=$(java -DuseCWDasROOT=true -jar ../.github/kolmafia.jar --CLI _ci_verify)
        if [[ $output != *"Script verification complete." ]]; then echo $output
          exit 1
        else
          echo "autoscend.ash verified!"      
        fi

        # Verify auto_pre_adv.ash
        echo "Verifying auto_pre_adv.ash..."
        echo "try { cli_execute('verify ${"auto_pre_adv.ash"}'); } finally { cli_execute('exit'); }" > scripts/_ci_verify.ash
        output=$(java -DuseCWDasROOT=true -jar ../.github/kolmafia.jar --CLI _ci_verify)
        if [[ $output != *"Script verification complete." ]]; then
          echo $output
          exit 1
        else
          echo "auto_pre_adv.ash verified!"      
        fi

        # Verify auto_post_adv.ash
        echo "Verifying auto_post_adv.ash..."
        echo "try { cli_execute('verify ${"auto_post_adv.ash"}'); } finally { cli_execute('exit'); }" > scripts/_ci_verify.ash
        output=$(java -DuseCWDasROOT=true -jar ../.github/kolmafia.jar --CLI _ci_verify)
        if [[ $output != *"Script verification complete." ]]; then
          echo $output
          exit 1
        else
          echo "auto_post_adv.ash verified!"      
        fi

        exit 0
